'use client'
import React from "react";
import Head from "next/head";
import Link from "next/link";
import Calendar from "@/components/Calendar";

import { api } from "@/utils/api";
import type { DateTime } from "@/utils/types";
import Spinner from "@/components/Spinner";

export default function Home() {

  const [date, setDate] = React.useState<DateTime>({
    justDate: null,
    dateTime: null
  })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {!date.dateTime && <Calendar setDate={setDate} date={date}/>}

        {date.dateTime && false ? <Menu /> : <div className="flex h-screen items-center justify-center"> <Spinner/> </div>}

      </main>
    </>
  );
}
